version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: sales-agent-backend
    env_file: .env
    volumes:
      - ./app.db:/app/app.db   # persist sqlite in project root
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: sales-agent-frontend
    environment:
      - STREAMLIT_PORT=8501
    ports:
      - "8501:8501"
    depends_on:
      - backend
